name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.left.svg

          # Options
          user: hhh2210
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_sections: user
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 6
#           plugin_languages_recent_days: 14
#           plugin_languages_recent_load: 300
#           plugin_languages_threshold: 13%
#           plugin_languages_other: true
          plugin_languages_ignored: html, css, 4D, q
          plugin_languages_details: bytes-size, percentage
#           plugin_languages_sections: most-used
#           plugin_languages_indepth: yes
          plugin_languages_aliases: Jupyter Notebook:ipynb
#           commits_authoring: 975062472@qq.com, tony031218@qq.com, tonycrane@foxmail.com, crane@manim.org.cn, tonycrane@zju.edu.cn, TonyCrane, Tony031218, 鹤翔万里
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 6
          plugin_starlists_languages_ignored: html
          plugin_starlists_languages_aliases: Jupyter Notebook:ipynb
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Learning
          # plugin_rss: yes
          # plugin_rss_source: https://blog.tonycrane.cc/atom.xml
          # plugin_rss_limit: 3
          config_order: followup, languages, starlists #, rss
